Use CLLD link builder for Concepticon links
clld/clics pull request #13
Opened 2018-08-21 12:40 UTC by chrzyki

See #11.

2018-08-21 13:34 UTC, xrotwang requested changes

2018-08-21 13:34 UTC, xrotwang commented on tests/test_functional.py
> +        ('get_html', '/contributions'),
The data table content will only be rendered, when called as XmlHttpRequest. There's a helper method of test app to do this: https://github.com/clld/pytest-clld/blob/e08137672df50e413db778856aa0674fbfba36d3/pytest_clld/_app.py#L63

2018-08-22 06:31 UTC, chrzyki commented on tests/test_functional.py
> +        ('get_html', '/contributions'),
Thanks! Updated the PR.

2018-09-06 12:12 UTC, xrotwang approved these changes

2018-09-06 12:13 UTC, merged